### ISSUE TITLE
NoSuchMethodError when calling getObjects() on zero results.

### ISSUE THREAD

**Issue by crtl** [knoxpo/dart_algolia#26]
Flutter version: 1.16.3

**Describe the bug**
When calling `getObjects` on `AlgoliaQuerySnapshot` will throw `NoSuchMethod error` if the query is empty.

```
E/flutter (32206): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'map' was called on null.
E/flutter (32206): Receiver: null
E/flutter (32206): Tried calling: map<AlgoliaObjectSnapshot>(Closure: (dynamic) => AlgoliaObjectSnapshot)
E/flutter (32206): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (32206): #1      new AlgoliaQuerySnapshot.fromMap (package:algolia/src/query_snapshot.dart:36:10)
E/flutter (32206): #2      AlgoliaQuery.getObjects (package:algolia/src/query.dart:77:33)
```

**Expected behavior**
Null or an empty array should be returned.

**Comment by leonus96** [comment]
Same problem, in which version did it work well?

**Comment by kdy1** [comment]
I fixed it and sent a pr.

In the meantime, you can yse my fork like

```yaml
  algolia:
    git: https://github.com/kdy1/dart_algolia.git
```
